const texts = {
  EN: {
    about: {
      intro:
        '"Genius, millionaire, playboy, philanthropist..." that is Tony Stark',
      about_greetigs: "👋 Hello, I'm Guillermo ",
      about:
        'I am the man of a thousand bootcamps, a tireless seeker of opportunities for growth, development and learning. Those are my values ​​"how you do one thing, you do all things." Although I define myself as a fullstack developer, I feel a deep attraction to the backend and everything involved with application cybersecurity. I hope that what you find in my profile is to your liking and of value to you and we can celebrate a happy meeting. Hugs.',
    },
    resume: "Check out my resume",
    age: "38 springs",
    projects: "Projects",
    textProject1: "Website urban nursery",
    textProject2: "App Role-playing games",
    textProject3: "Node SSR virtual store",
    textProject4: "Sample label generator",
    email: "Email me !",
    music: "Music",
    hobbies: "Hobbies",
    contact: "Send me a message",
    modal: {
      title: "Please write your message",
      btn_send: "Send",
      btn_close: "Close",
    },
    hobbies: {
      title: "Hobbies",
      hobbie1: "Tarot and chamanism",
      hobbie2: "Elaborate craft beers",
      hobbie3: "Read",
      hobbie4: "Automations with Arduinos",
      hobbie5: "Motorcycle trips",
      hobbie6: "Play many instruments",
      hobbie7: "Design and 3d printing",
    },
  },
  ES: {
    about: {
      intro: '"Genio, millonario, playboy, filántropo..." ese es Tony Stark',
      about_greetigs: "👋 Hola, soy Guillermo",
      about:
        'Soy el hombre de los mil bootcamps, buscador incasable de oportunidades de crecimiento, desarrollo y aprendizaje. Esos son mis valores "como haces una cosa, haces todas las cosas". Si bien me defino como un desarrollador fullstack, siento una profunda atracción por el backend y todo lo involucrado con la ciberseguridad de aplicaciones. Espero que lo que encuentres en mi perfil sea de tu agrado y de valor para ti y podamos celabrar un feliz encuentro. Abrazos.',
    },
    resume: "Hecha un vistazo a mi CV",
    age: "38 primaveras",
    projects: "Proyectos",
    textProject1: "Website vivero urbano",
    textProject2: "App juegos de Rol",
    textProject3: " NodeTienda virtual SSR",
    textProject4: "Generador de etiquetas de muestras",
    email: "¡Envíame un correo!",
    music: "Música",
    hobbies: {
      title: "Pasatiempos",
      hobbie1: "Tarot y chamanismo",
      hobbie2: "Elaborar cervezas artesanales",
      hobbie3: "Leer",
      hobbie4: "automatizaciones con Arduinos",
      hobbie5: "Viajes en moto",
      hobbie6: "tocar muchos instrumentos",
      hobbie7: "diseño e impresión 3d",
    },
    contact: "Envíame un mensaje",
    modal: {
      title: "Por favor esciba su mensaje",
      btn_send: "Enviar",
      btn_close: "Cerrar",
    },
  },
};
